# Settings for the book which can be called within the book source files
#
# in book/book.html.erb
#
#      <p><b>Version:</b> <%= @book.epub.version %></p>
#
#   or
#
#      <% if @book.epub.version == '1.0.0' %>
#        <p>Whew! We made it!</p>
#      <% end %>

title: Agile Book Development with Bookshop
subtitle: Designing Your Book For Tomorrow
isbn: 1234567891011     # ISBN-13
creator: 
publisher: BlueHead Publishing
contributor: 'Dave Thompson'
date: 2012-03-31
type:
format:
identifier: 1234567891011
source: 
language: en
relation:
coverage:
rights:
version: 0.1.0



# Place the pdf specific settings here. Use whatever you want.
# You can use these settings in your source layouts by using a tag
#   in book.html.erb you could use <%= @book.pdf.title %>
pdf:
  title: Agile Book Development with Bookshop


# Place the epub specific settings here.
epub:
  title: Agile Book Development with Bookshop
  version: 0.1.1


# Place the html specific settings here
html:
  title: Agile Book Development with Bookshop


# You can add any additional variables you want
#
# foo:
#   bar: foobar
#
#   in book.html.erb you can then use <%= @book.foo.bar %>  # --> foobar